name: "Omega Zirkel GPS (com.vms.GPS)"
main: de.omegazirkel.risingworld.GPS
version: 1.5.1
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "GPS Plugin, originally written by Miwarre"
license: EMS
website: coming soon